# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 13:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyCNY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_rate', models.FloatField(default=0)),
                ('currency_final', models.FloatField(default=0)),
                ('pub_date', models.DateField(default=datetime.date(2016, 10, 4), verbose_name='published date')),
                ('nation', models.CharField(default='CNY', max_length=3)),
                ('title', models.CharField(default='위안화', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyEUR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_rate', models.FloatField(default=0)),
                ('currency_final', models.FloatField(default=0)),
                ('pub_date', models.DateField(default=datetime.date(2016, 10, 4), verbose_name='published date')),
                ('nation', models.CharField(default='EUR', max_length=3)),
                ('title', models.CharField(default='유로화', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyGBP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_rate', models.FloatField(default=0)),
                ('currency_final', models.FloatField(default=0)),
                ('pub_date', models.DateField(default=datetime.date(2016, 10, 4), verbose_name='published date')),
                ('nation', models.CharField(default='GBP', max_length=3)),
                ('title', models.CharField(default='파운드', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyJPY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_rate', models.FloatField(default=0)),
                ('currency_final', models.FloatField(default=0)),
                ('pub_date', models.DateField(default=datetime.date(2016, 10, 4), verbose_name='published date')),
                ('nation', models.CharField(default='JPY', max_length=3)),
                ('title', models.CharField(default='엔화', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyKRW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_rate', models.FloatField(default=0)),
                ('currency_final', models.FloatField(default=0)),
                ('pub_date', models.DateField(default=datetime.date(2016, 10, 4), verbose_name='published date')),
                ('nation', models.CharField(default='KRW', max_length=3)),
                ('title', models.CharField(default='한국돈', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
